all:
  children:
    web:
      hosts:
        node02:
          ansible_host: 10.0.0.92
    db:
      hosts:
        node03:
          ansible_host: 10.0.0.93
    admin:
      hosts:
        node01:
          ansible_host: 10.0.0.91
