- name: Installer vim
  hosts: all
  become: yes
  tasks:
    - name: Installer le paquet vim
      ansible.builtin.apt:
        name: vim
        state: present
        update_cache: yes

- name: Verif /etc/passwd
  hosts: all
  gather_facts: no
  tasks:
    - name: Vérifier si /etc/passwd existe
      ansible.builtin.stat:
        path: /etc/passwd
      register: passwd_file

    - name: Afficher le résultat
      debug:
        msg: "/etc/passwd existe"
      when: passwd_file.stat.exists

    - name: Afficher le résultat
      debug:
        msg: "/etc/passwd n'existe pas"
      when: not passwd_file.stat.exists
