all:
  children:
    webserversapache:
      hosts:
        node01:
          ansible_host: 10.0.0.92
        node02:
          ansible_host: 10.0.0.93
    webserversnginx:
      hosts:
        node01:
          ansible_host: 10.0.0.91
