---
- name: Installer les dépendances nécessaires
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apache2
    - php
    - php-mysql
    - libapache2-mod-php
    - php-gd
    - php-mbstring
    - php-xml
    - php-curl

- name: Télécharger WordPress
  get_url:
    url: "https://wordpress.org/latest.tar.gz"
    dest: "/tmp/wordpress.tar.gz"

- name: Extraire WordPress
  unarchive:
    src: "/tmp/wordpress.tar.gz"
    dest: "/var/www/html"
    remote_src: yes

- name: Configurer les permissions pour WordPress
  file:
    path: "/var/www/html/wordpress"
    owner: www-data
    group: www-data
    mode: '0644'
    recurse: yes
  notify: confwpok

