---
# Default variables for WordPress installation
wordpress_version: latest
php_version: "7.4"
mysql_root_password: "root_password"
wordpress_db_name: "wordpress"
wordpress_db_user: "wordpress_user"
wordpress_db_password: "wordpress_password"
wordpress_db_host: "db"
