all:
  children:
    webservers:
      hosts:
        node01:
          ansible_host: 10.0.0.92
        node02:
          ansible_host: 10.0.0.93
    database:
      hosts:
        node01:
          ansible_host: 10.0.0.91
